package com.grippo.domain.state.metrics.profile

import com.grippo.core.state.metrics.profile.GoalFitRuleState
import com.grippo.data.features.api.metrics.profile.models.GoalFitRule

public fun GoalFitRule.toState(): GoalFitRuleState = when (this) {
    GoalFitRule.BUILD_MUSCLE_HYPERTROPHY_REP_RANGE_SHARE ->
        GoalFitRuleState.BUILD_MUSCLE_HYPERTROPHY_REP_RANGE_SHARE

    GoalFitRule.BUILD_MUSCLE_WEEKLY_SETS_PER_PRIMARY_GROUP ->
        GoalFitRuleState.BUILD_MUSCLE_WEEKLY_SETS_PER_PRIMARY_GROUP

    GoalFitRule.BUILD_MUSCLE_WEEKLY_FREQUENCY_PER_PRIMARY_GROUP ->
        GoalFitRuleState.BUILD_MUSCLE_WEEKLY_FREQUENCY_PER_PRIMARY_GROUP

    GoalFitRule.BUILD_MUSCLE_ACCESSORY_INVERSION ->
        GoalFitRuleState.BUILD_MUSCLE_ACCESSORY_INVERSION

    GoalFitRule.BUILD_MUSCLE_LOAD_PROGRESSION ->
        GoalFitRuleState.BUILD_MUSCLE_LOAD_PROGRESSION

    GoalFitRule.GET_STRONGER_COMPOUND_PRESENCE ->
        GoalFitRuleState.GET_STRONGER_COMPOUND_PRESENCE

    GoalFitRule.GET_STRONGER_HEAVY_INTENSITY_SHARE ->
        GoalFitRuleState.GET_STRONGER_HEAVY_INTENSITY_SHARE

    GoalFitRule.GET_STRONGER_STRENGTH_REP_RANGE_SHARE ->
        GoalFitRuleState.GET_STRONGER_STRENGTH_REP_RANGE_SHARE

    GoalFitRule.GET_STRONGER_COMPOUND_TO_ISOLATION_RATIO ->
        GoalFitRuleState.GET_STRONGER_COMPOUND_TO_ISOLATION_RATIO

    GoalFitRule.GET_STRONGER_STRENGTH_PROGRESSION ->
        GoalFitRuleState.GET_STRONGER_STRENGTH_PROGRESSION

    GoalFitRule.MAINTAIN_WORK_BALANCE_SKEW ->
        GoalFitRuleState.MAINTAIN_WORK_BALANCE_SKEW

    GoalFitRule.MAINTAIN_GROUP_COVERAGE ->
        GoalFitRuleState.MAINTAIN_GROUP_COVERAGE

    GoalFitRule.MAINTAIN_WEEKLY_FREQUENCY ->
        GoalFitRuleState.MAINTAIN_WEEKLY_FREQUENCY

    GoalFitRule.MAINTAIN_WEEKLY_VOLUME_STABILITY ->
        GoalFitRuleState.MAINTAIN_WEEKLY_VOLUME_STABILITY

    GoalFitRule.GENERAL_FITNESS_QUALITY_VARIETY ->
        GoalFitRuleState.GENERAL_FITNESS_QUALITY_VARIETY

    GoalFitRule.GENERAL_FITNESS_GROUP_COVERAGE ->
        GoalFitRuleState.GENERAL_FITNESS_GROUP_COVERAGE

    GoalFitRule.GENERAL_FITNESS_WEEKLY_FREQUENCY ->
        GoalFitRuleState.GENERAL_FITNESS_WEEKLY_FREQUENCY

    GoalFitRule.GENERAL_FITNESS_WORK_BALANCE_SKEW ->
        GoalFitRuleState.GENERAL_FITNESS_WORK_BALANCE_SKEW

    GoalFitRule.LOSE_FAT_SESSION_ADHERENCE ->
        GoalFitRuleState.LOSE_FAT_SESSION_ADHERENCE

    GoalFitRule.LOSE_FAT_RESISTANCE_PRESENCE ->
        GoalFitRuleState.LOSE_FAT_RESISTANCE_PRESENCE

    GoalFitRule.LOSE_FAT_WEEKLY_VOLUME_TREND ->
        GoalFitRuleState.LOSE_FAT_WEEKLY_VOLUME_TREND

    GoalFitRule.RETURN_TO_TRAINING_WEEKLY_FREQUENCY ->
        GoalFitRuleState.RETURN_TO_TRAINING_WEEKLY_FREQUENCY

    GoalFitRule.RETURN_TO_TRAINING_LOAD_RAMP_GENTLE ->
        GoalFitRuleState.RETURN_TO_TRAINING_LOAD_RAMP_GENTLE

    GoalFitRule.RETURN_TO_TRAINING_INTENSITY_FLOOR ->
        GoalFitRuleState.RETURN_TO_TRAINING_INTENSITY_FLOOR
}
