// Stable machine codes for the component pipeline (FIGMA_COMPONENTS.md §26).
// Stored codes are contract; UI copy localizes them separately. One owner:
// every producer/validator/server projection imports this set instead of
// minting strings. Adapter-foundation codes (PROJECT_ADAPTER_*) are owned by
// orchestrator/figma/runtime/error-codes.mjs; this set covers the component
// domain only.
export const COMPONENT_ERROR_CODES = Object.freeze({
  COMPONENT_DESIGN_SOURCE_NOT_SYNCED: 'COMPONENT_DESIGN_SOURCE_NOT_SYNCED',
  COMPONENT_DESIGN_CAPTURE_INVALID: 'COMPONENT_DESIGN_CAPTURE_INVALID',
  COMPONENT_DESIGN_CAPTURE_INCOMPLETE: 'COMPONENT_DESIGN_CAPTURE_INCOMPLETE',
  COMPONENT_DESIGN_ACCESS_DEGRADED: 'COMPONENT_DESIGN_ACCESS_DEGRADED',
  COMPONENT_DESIGN_ABSENCE_UNPROVEN: 'COMPONENT_DESIGN_ABSENCE_UNPROVEN',
  COMPONENT_DESIGN_SCOPE_CHANGED: 'COMPONENT_DESIGN_SCOPE_CHANGED',
  COMPONENT_PROJECT_INVENTORY_INCOMPLETE: 'COMPONENT_PROJECT_INVENTORY_INCOMPLETE',
  COMPONENT_PROJECT_DUPLICATE_ID: 'COMPONENT_PROJECT_DUPLICATE_ID',
  COMPONENT_PROPERTY_UNSUPPORTED: 'COMPONENT_PROPERTY_UNSUPPORTED',
  COMPONENT_VARIANT_CAPTURE_INCOMPLETE: 'COMPONENT_VARIANT_CAPTURE_INCOMPLETE',
  COMPONENT_VARIANT_SPACE_TOO_LARGE: 'COMPONENT_VARIANT_SPACE_TOO_LARGE',
  COMPONENT_MAPPING_INVALID: 'COMPONENT_MAPPING_INVALID',
  COMPONENT_MAPPING_CONFLICT: 'COMPONENT_MAPPING_CONFLICT',
  COMPONENT_MAPPING_REVISION_CONFLICT: 'COMPONENT_MAPPING_REVISION_CONFLICT',
  COMPONENT_DESIGN_GENERATION_CONFLICT: 'COMPONENT_DESIGN_GENERATION_CONFLICT',
  COMPONENT_PROJECT_INVENTORY_CONFLICT: 'COMPONENT_PROJECT_INVENTORY_CONFLICT',
  COMPONENT_MAPPING_OPERATION_CONFLICT: 'COMPONENT_MAPPING_OPERATION_CONFLICT',
  COMPONENT_MAPPING_TARGET_MISSING: 'COMPONENT_MAPPING_TARGET_MISSING',
  COMPONENT_MAPPING_AMBIGUOUS: 'COMPONENT_MAPPING_AMBIGUOUS',
  COMPONENT_COMPARISON_LIMIT_EXCEEDED: 'COMPONENT_COMPARISON_LIMIT_EXCEEDED',
  COMPONENT_COMPARISON_BASELINE_INELIGIBLE: 'COMPONENT_COMPARISON_BASELINE_INELIGIBLE',
  COMPONENT_FINDING_STALE: 'COMPONENT_FINDING_STALE',
  COMPONENT_TASK_BINDING_INVALID: 'COMPONENT_TASK_BINDING_INVALID',
  COMPONENT_TASK_BINDING_AMBIGUOUS: 'COMPONENT_TASK_BINDING_AMBIGUOUS',
  COMPONENT_TASK_BINDING_STALE: 'COMPONENT_TASK_BINDING_STALE',
  COMPONENT_MAPPING_PUBLICATION_RECOVERY_REQUIRED: 'COMPONENT_MAPPING_PUBLICATION_RECOVERY_REQUIRED',
  COMPONENT_GENERATION_RESYNC_REQUIRED: 'COMPONENT_GENERATION_RESYNC_REQUIRED',
  COMPONENT_EXTRACTION_REGRESSION: 'COMPONENT_EXTRACTION_REGRESSION',
  COMPONENT_COMPARATOR_OUTPUT_INVALID: 'COMPONENT_COMPARATOR_OUTPUT_INVALID',
  COMPONENT_GENERATION_ARTIFACT_INVALID: 'COMPONENT_GENERATION_ARTIFACT_INVALID',
  COMPONENT_TOKEN_REFERENCE_UNCOVERED: 'COMPONENT_TOKEN_REFERENCE_UNCOVERED'
})
