// Stable machine codes owned by the shared adapter foundation (config loader,
// registry, trusted runner, input snapshot). Domain-specific codes live with
// their domain (orchestrator/figma/tokens/error-codes.mjs); no code is defined
// twice.
export const ADAPTER_ERROR_CODES = Object.freeze({
  PROJECT_ADAPTERS_UNCONFIGURED: 'PROJECT_ADAPTERS_UNCONFIGURED',
  PROJECT_ADAPTER_CONFIG_INVALID: 'PROJECT_ADAPTER_CONFIG_INVALID',
  PROJECT_ADAPTER_UNKNOWN: 'PROJECT_ADAPTER_UNKNOWN',
  PROJECT_ADAPTER_PROTOCOL_UNSUPPORTED: 'PROJECT_ADAPTER_PROTOCOL_UNSUPPORTED',
  PROJECT_ADAPTER_RUNTIME_UNAVAILABLE: 'PROJECT_ADAPTER_RUNTIME_UNAVAILABLE',
  PROJECT_ADAPTER_INPUT_OUTSIDE_ROOT: 'PROJECT_ADAPTER_INPUT_OUTSIDE_ROOT',
  PROJECT_ADAPTER_OUTPUT_INVALID: 'PROJECT_ADAPTER_OUTPUT_INVALID',
  PROJECT_ADAPTER_TIMEOUT: 'PROJECT_ADAPTER_TIMEOUT',
  ADAPTER_INPUT_SNAPSHOT_LIMIT: 'ADAPTER_INPUT_SNAPSHOT_LIMIT',
  ADAPTER_INPUT_SNAPSHOT_UNSAFE: 'ADAPTER_INPUT_SNAPSHOT_UNSAFE'
})
