package com.grippo.data.features.api.metrics.profile.models

public enum class GoalFitRule {
    BUILD_MUSCLE_HYPERTROPHY_REP_RANGE_SHARE,
    BUILD_MUSCLE_WEEKLY_SETS_PER_PRIMARY_GROUP,
    BUILD_MUSCLE_WEEKLY_FREQUENCY_PER_PRIMARY_GROUP,
    BUILD_MUSCLE_ACCESSORY_INVERSION,
    BUILD_MUSCLE_LOAD_PROGRESSION,

    GET_STRONGER_COMPOUND_PRESENCE,
    GET_STRONGER_HEAVY_INTENSITY_SHARE,
    GET_STRONGER_STRENGTH_REP_RANGE_SHARE,
    GET_STRONGER_COMPOUND_TO_ISOLATION_RATIO,
    GET_STRONGER_STRENGTH_PROGRESSION,

    MAINTAIN_WORK_BALANCE_SKEW,
    MAINTAIN_GROUP_COVERAGE,
    MAINTAIN_WEEKLY_FREQUENCY,
    MAINTAIN_WEEKLY_VOLUME_STABILITY,

    GENERAL_FITNESS_QUALITY_VARIETY,
    GENERAL_FITNESS_GROUP_COVERAGE,
    GENERAL_FITNESS_WEEKLY_FREQUENCY,
    GENERAL_FITNESS_WORK_BALANCE_SKEW,

    LOSE_FAT_SESSION_ADHERENCE,
    LOSE_FAT_RESISTANCE_PRESENCE,
    LOSE_FAT_WEEKLY_VOLUME_TREND,

    RETURN_TO_TRAINING_WEEKLY_FREQUENCY,
    RETURN_TO_TRAINING_LOAD_RAMP_GENTLE,
    RETURN_TO_TRAINING_INTENSITY_FLOOR,
}