#!/usr/bin/env python3
"""Stamp the vendored-copy integrity manifest: orchestrator/template-manifest.json.

A bootstrapped product is a VENDORED copy of the template's orchestrator/** tree
with no auto-propagation — copies rot silently. This generator hashes every
TEMPLATE-OWNED file under orchestrator/ (sha256) into a committed manifest that
ships INSIDE the copy, so `check-integrity.mjs` can later report, offline:
which files were locally modified / deleted, what appeared that the template
never shipped, and how old the copy's stamp is.

LIFECYCLE:
  - Stamped at bootstrap (launch.md Step 14, right after install-skills.sh) and
    re-stamped ONLY by an explicit `sync-from-template.sh --apply`.
  - NEVER auto-regenerated by a product's pre-commit hook or any daemon: an
    auto-regen would re-baseline local drift as "clean" on every commit and the
    sensor could never report rot again (the self-laundering trap).
  - In the template repo itself the manifest is not continuously regenerated
    either; run this manually when cutting/refreshing a copy.

The EXCLUSION SET below is the correctness surface: it must skip everything
per-product (config, tasks, caches, populated snapshots, secrets) or a pristine
fresh copy reports "modified" on day one and operators learn to ignore the
sensor. It is single-sourced HERE and embedded into the manifest (`excludes`),
so the checker and the sync tool read the rules from the artifact instead of
carrying divergent copies. Keep it in lockstep with the root .gitignore and the
launch.md Step 2.5 ignore block.

Usage:
  python3 _generate_template_manifest.py                    # write orchestrator/template-manifest.json
  python3 _generate_template_manifest.py --print            # manifest to stdout, no write
  python3 _generate_template_manifest.py --print-exclusions # exclusion rules to stdout
  python3 _generate_template_manifest.py --root <path>      # operate on another product root
"""
import datetime
import hashlib
import json
import os
import stat
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
MANIFEST_REL = os.path.join("orchestrator", "template-manifest.json")

# All paths are product-root-relative with forward slashes.
EXCLUDES = {
    # Whole per-product / runtime subtrees (dir prefixes, trailing slash).
    # Curated figma/tokens source and the manifests/.gitkeep placeholder are
    # template-owned; all generated Figma runtime data lives under .cache/.
    "prefixes": [
        "orchestrator/.cache/",
        "orchestrator/tasks/backlog/",
        "orchestrator/tasks/pending/",
        "orchestrator/tasks/todo/",
        "orchestrator/tasks/done/",
        "orchestrator/tasks/evidence/",
        "orchestrator/api-contract/spec/",
        "orchestrator/api-contract/manifests/",
        "orchestrator/api-contract/.secrets/",
    ],
    # Per-product / generated single files.
    "exact": [
        "orchestrator/template-manifest.json",   # never hash the artifact itself
        "orchestrator/project-config.md",
        "orchestrator/.arch-map.json",
        "orchestrator/tasks/INDEX.json",
        "orchestrator/figma/.account.json",
        "orchestrator/figma/project-adapters.json",
        "orchestrator/api-contract/environments.json",
    ],
    # Pruned anywhere in the walk, by basename. `.env` (any sidecar) is the
    # per-product secrets class — hashing one would both false-flag products and
    # let sync --apply copy a maintainer's real credentials into a product.
    "basenames": ["node_modules", "__pycache__", ".DS_Store", ".idea", "temp", ".env"],
    "basenameSuffixes": [".pyc"],
    "basenamePrefixes": [],
}


def _basename_excluded(name):
    if name in EXCLUDES["basenames"]:
        return True
    if any(name.endswith(s) for s in EXCLUDES["basenameSuffixes"]):
        return True
    return any(name.startswith(p) for p in EXCLUDES["basenamePrefixes"])


def excluded(rel):
    if rel in EXCLUDES["exact"]:
        return True
    return any(rel.startswith(p) for p in EXCLUDES["prefixes"])


def collect_files(root):
    """sha256 of every template-owned file under <root>/orchestrator/."""
    base = os.path.join(root, "orchestrator")
    if os.path.islink(base):
        sys.exit(f"template-manifest generator: unsafe symlink orchestrator root under {root!r}")
    if not os.path.isdir(base):
        sys.exit(f"template-manifest generator: no orchestrator/ under {root!r}")
    files = {}

    def _walk_error(err):
        # An unreadable directory must be LOUD on both sides (the JS checker
        # hard-fails too) — silently omitting a subtree would stamp a baseline
        # with a hole in it.
        sys.exit(f"template-manifest generator: cannot read {getattr(err, 'filename', '?')!r}: {err}")

    for dirpath, dirnames, filenames in os.walk(base, onerror=_walk_error):
        # Excluded product/runtime trees are ignored. A template-owned symlink
        # or special directory is never silently omitted: stamping around it
        # would launder an unsafe copy into a false-clean baseline.
        kept_dirs = []
        for name in sorted(dirnames):
            full = os.path.join(dirpath, name)
            rel = os.path.relpath(full, root).replace(os.sep, "/") + "/"
            if _basename_excluded(name) or excluded(rel):
                continue
            try:
                mode = os.lstat(full).st_mode
            except OSError as err:
                _walk_error(err)
            if stat.S_ISLNK(mode):
                sys.exit(f"template-manifest generator: unsafe symlink directory {rel!r}")
            if not stat.S_ISDIR(mode):
                sys.exit(f"template-manifest generator: unsafe non-directory entry {rel!r}")
            kept_dirs.append(name)
        dirnames[:] = kept_dirs
        for name in sorted(filenames):
            if _basename_excluded(name):
                continue
            full = os.path.join(dirpath, name)
            rel = os.path.relpath(full, root).replace(os.sep, "/")
            if excluded(rel):
                continue
            try:
                mode = os.lstat(full).st_mode
            except OSError as err:
                _walk_error(err)
            if stat.S_ISLNK(mode):
                sys.exit(f"template-manifest generator: unsafe symlink file {rel!r}")
            if not stat.S_ISREG(mode):
                sys.exit(f"template-manifest generator: unsafe special file {rel!r}")
            h = hashlib.sha256()
            with open(full, "rb") as fh:
                for chunk in iter(lambda: fh.read(1 << 16), b""):
                    h.update(chunk)
            files[rel] = h.hexdigest()
    return files


def stamp_commit(root):
    """HEAD of the tree being STAMPED, '-dirty'-suffixed when the working tree
    differs from it. Honest semantics (not "the template's commit"): at a
    sync --apply the stamped tree IS the template, so this records the
    template's commit; at bootstrap Step 14 it records the fresh PRODUCT's
    own commit (or 'unknown' pre-git-init) — the checker labels it as such."""
    try:
        head = subprocess.run(["git", "-C", root, "rev-parse", "HEAD"],
                              capture_output=True, encoding="utf-8", timeout=10)
        if head.returncode != 0 or not head.stdout.strip():
            return "unknown"
        commit = head.stdout.strip()
        dirty = subprocess.run(["git", "-C", root, "status", "--porcelain"],
                               capture_output=True, encoding="utf-8", timeout=10)
        if dirty.returncode == 0 and dirty.stdout.strip():
            commit += "-dirty"
        return commit
    except Exception:
        return "unknown"


def build_manifest(root):
    files = collect_files(root)
    return {
        "version": 1,
        "stampCommit": stamp_commit(root),
        "stampedAt": datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "excludes": EXCLUDES,
        "count": len(files),
        "files": files,
    }


def main():
    args = sys.argv[1:]
    root = DEFAULT_ROOT
    if "--root" in args:
        i = args.index("--root")
        if i + 1 >= len(args):
            sys.exit("usage: _generate_template_manifest.py [--print|--print-exclusions] [--root <path>]")
        root = os.path.abspath(args[i + 1])
        del args[i:i + 2]
    if args == ["--print-exclusions"]:
        print(json.dumps(EXCLUDES, indent=1, sort_keys=True))
        return
    if args not in ([], ["--print"]):
        sys.exit("usage: _generate_template_manifest.py [--print|--print-exclusions] [--root <path>]")
    manifest = build_manifest(root)
    text = json.dumps(manifest, indent=1, sort_keys=True) + "\n"
    if args == ["--print"]:
        sys.stdout.write(text)
        return
    out = os.path.join(root, MANIFEST_REL)
    with open(out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print(f"stamped {out}: {manifest['count']} files @ {manifest['stampCommit'][:18]}")


if __name__ == "__main__":
    main()
